### ISSUE TITLE
GTA's MemoryMgr game version issue

### ISSUE THREAD

**Issue by gennariarmando** [CookiePLMonster/ModUtils#12]
Tried using latest "MemoryMgr.GTA.h", seems like it sets the wrong version, at least for GTA3 1.0.
Not sure what's going on so I thought I might open an issue,

https://github.com/CookiePLMonster/ModUtils/blob/f69eb3956d9349ea820120b218676d74589ea0a2/MemoryMgr.GTA.h#L64

Previously was checked as follows:
`if (*(uint32_t*)0x5C1E70 == 0x53E58955) *bVer = 0;`

**Comment by CookiePLMonster** [comment]
It's been changed so it doesn't check the entrypoint, in case it's re-routed. Is the revised check wrong maybe? I regularly test on III 1.0 and I've not noticed any fixes regressing.

**Comment by gennariarmando** [comment]
The check looks fine to me, wasn't sure what was going on but it's probably something wrong on my end. Thank you.
