### ISSUE TITLE
Build error with MSVC 19.41

### ISSUE THREAD

**Issue by emoose** [CookiePLMonster/ModUtils#13]
Hi, thanks for the work on ModUtils, the Memory & Pattern code has been great to use!

OutRun2006Tweaks makes use of it, but recently github actions have been failing to build, eg: https://github.com/emoose/OutRun2006Tweaks/actions/runs/10584985216/job/29330534627
But the commit after that one built fine: https://github.com/emoose/OutRun2006Tweaks/actions/runs/10585142075/job/29331059552

Only difference I could see is the failed build using 19.41.34120.0 while successful build used the older 19.40.33813.0, updating my local VS also gives the same build error.

Not sure what could be wrong with the lines it complains about though: https://github.com/CookiePLMonster/ModUtils/blob/3d5474e8d5f8732f2306409c58890e5578d1eed7/Patterns.h#L74-L75
Maybe something has changed and an extra include is now required there?

E: ah maybe https://github.com/microsoft/STL/pull/4633 is the cause, adding `_LEGACY_CODE_ASSUMES_STRING_VIEW_INCLUDES_XSTRING` seems to let the build work.

**Comment by CookiePLMonster** [comment]
Yeah, sounds like `#include <string>` is now needed, notice I have `<string_view>` included but not `<string>`.

Feel free to PR a fix!
